<?xml version="1.0"?>
<project name="blueseer" default="main" basedir=".">
     <!-- Sets variables which can later be used. -->
     <!-- The value of a property is accessed via ${} -->
     <property name="src.dir" location="src" />
     <property name="test.dir" location="test" />
     <property name="build.dir" location="${test.dir}/build" />
     <property name="dist.dir" location="${test.dir}/dist" />
     <property name="lib.dir" location="lib" />
     <property name="JDK" location="/path/to/your/jdk" />
     <property name="javac" location="${JDK}/bin/javac" />
     <property name="java" location="${JDK}/bin/java" />
     <property name="classpath.property"
            value="${test.dir}/dist/" />

     <path id="build.classpath">
         <fileset dir="${lib.dir}">
             <include name="**/*.jar" />
         </fileset>
     </path>

      <path id="run.classpath">
        <fileset dir="${test.dir}/dist" includes="*.jar"/>
        <fileset dir="${test.dir}" includes="*.jar"/>
     </path>


     <!-- Deletes the existing build, docs and dist directory-->
     <target name="clean">
         <delete dir="${build.dir}" />
         <delete dir="${dist.dir}" />
     </target>

     <!-- Creates the  build, docs and dist directory-->
     <target name="makedir">
         <mkdir dir="${build.dir}" />
         <mkdir dir="${dist.dir}" />
         <copy todir="${dist.dir}" overwrite="true">
          <fileset dir="${lib.dir}"/>
          </copy>
     </target>

     <!-- Compiles the java code (including the usage of library for JUnit -->
     <target name="compile" depends="clean, makedir">
         <javac executable="${javac}" fork="yes" srcdir="${src.dir}"
destdir="${build.dir}" classpathref="build.classpath"
includeantruntime="false" debug="true">
         </javac>
     </target>


     <!--Creates the deployable jar file  -->
     <target name="jar" depends="compile">
         <jar destfile="${dist.dir}\blueseer.jar" basedir="${build.dir}">
                <fileset dir="${src.dir}"
includes="images/**/*.png,images/**/*.gif,resources/**/*.properties" />
                <!--    <fileset dir="${lib.dir}" includes="**/*.jar"/> -->
             <manifest>
                 <attribute name="Main-Class" value="bsmf" />
             </manifest>
         </jar>
     </target>



<target name="run">
     <path id="runtime.path">
            <fileset dir="${test.dir}/dist" includes="*.jar"/>
           <!-- <fileset dir="lib" includes="*.jar"/> -->
     </path>
     <echo>running in ....${test.dir}</echo>
    <java classname="bsmf.MainFrame" jvm="${java}" fork="true"
classpathref="runtime.path" dir="${test.dir}">
            <arg value="-debug"/>
            <jvmarg
value="-Djava.util.logging.config.file=bslogging.properties"/>
         </java>
</target>


     <target name="main" depends="compile, jar">
         <description>Main target</description>
     </target>

</project>
