/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.blueseer.prd;

import bsmf.MainFrame;
import com.blueseer.utl.BlueSeerUtils;
import java.awt.Color;
import java.awt.Component;
import java.awt.FileDialog;
import java.awt.Frame;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import static bsmf.MainFrame.checkperms;
import static bsmf.MainFrame.con;
import static bsmf.MainFrame.db;
import static bsmf.MainFrame.driver;
import static bsmf.MainFrame.menumap;
import static bsmf.MainFrame.mydialog;
import static bsmf.MainFrame.panelmap;
import static bsmf.MainFrame.pass;
import static bsmf.MainFrame.url;
import static bsmf.MainFrame.user;

/**
 *
 * @author vaughnte
 */
public class ScrapReportPanel extends javax.swing.JPanel {
 
    /**
     * Creates new form ScrapReportPanel
     */
    
     class MyTableModel extends DefaultTableModel {  
      
        public MyTableModel(Object rowData[][], Object columnNames[]) {  
             super(rowData, columnNames);  
          }  
         
        @Override  
          public Class getColumnClass(int col) {  
            if (col == 2 || col == 3 || col == 4)       
                return Double.class;  
            else return String.class;  //other columns accept String values  
        }  
      @Override  
      public boolean isCellEditable(int row, int col) {  
        if (col == 0)       //first column will be uneditable  
            return false;  
        else return true;  
      }  
       
        }    
    
     class SomeRenderer extends DefaultTableCellRenderer {
        
    public Component getTableCellRendererComponent(JTable table,
            Object value, boolean isSelected, boolean hasFocus, int row,
            int column) {

        Component c = super.getTableCellRendererComponent(table,
                value, isSelected, hasFocus, row, column);

       
            if (column == 0)
            c.setForeground(Color.BLUE);
            else
                c.setBackground(table.getBackground());
       
        return c;
    }
    }
        
        
    public ScrapReportPanel() {
        initComponents();
    }

    public void initvars(String arg) {
         java.util.Date now = new java.util.Date();
         dcFrom.setDate(now);
         dcTo.setDate(now);
         cbkeydate.setSelected(true);
         cbassydate.setSelected(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dcFrom = new com.toedter.calendar.JDateChooser();
        dcTo = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        btRun = new javax.swing.JButton();
        fromPart = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        toPart = new javax.swing.JTextField();
        fromCode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        toCode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablescrap = new javax.swing.JTable();
        btexport = new javax.swing.JButton();
        labelcount = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelqty = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labeldollar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbsumpart = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        cbsumcode = new javax.swing.JCheckBox();
        cbassydate = new javax.swing.JCheckBox();
        cbkeydate = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(0, 102, 204));

        jLabel2.setText("From Date");

        dcFrom.setDateFormatString("yyyy-MM-dd");

        dcTo.setDateFormatString("yyyy-MM-dd");

        jLabel3.setText("To Date");

        btRun.setText("Run");
        btRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRunActionPerformed(evt);
            }
        });

        jLabel1.setText("From Part");

        jLabel4.setText("To Part");

        jLabel5.setText("From Code");

        jLabel6.setText("To Code");

        tablescrap.setAutoCreateRowSorter(true);
        tablescrap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablescrap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablescrapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablescrap);

        btexport.setText("Export");
        btexport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexportActionPerformed(evt);
            }
        });

        labelcount.setText("0");

        jLabel7.setText("Count");

        labelqty.setText("0");

        jLabel8.setText("Qty");

        labeldollar.setBackground(new java.awt.Color(195, 129, 129));
        labeldollar.setText("0");

        jLabel9.setText("$");

        cbsumpart.setText("Part");

        jLabel10.setText("Summarize");

        cbsumcode.setText("Code");

        cbassydate.setText("AssyDate");

        cbkeydate.setText("KeyDate");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dcTo, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(dcFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fromPart)
                            .addComponent(toPart, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fromCode, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toCode, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btRun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btexport))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbsumpart)
                                .addGap(12, 12, 12)
                                .addComponent(cbsumcode)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelcount, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbassydate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbkeydate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labeldollar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelqty, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dcFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(fromPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(toPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbassydate)
                            .addComponent(cbkeydate)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fromCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(toCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btRun)
                                .addComponent(btexport))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbsumpart)
                                .addComponent(jLabel10)
                                .addComponent(cbsumcode))
                            .addGap(25, 25, 25)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(labelcount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(labelqty, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(labeldollar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRunActionPerformed

    
try {
            Class.forName(driver).newInstance();
            con = DriverManager.getConnection(url + db, user, pass);
            try {
                Statement st = con.createStatement();
                ResultSet res = null;

                int qty = 0;
                double dol = 0;
                DecimalFormat df = new DecimalFormat("###,###,###.##");
                DateFormat dfdate = new SimpleDateFormat("yyyy-MM-dd");
                int i = 0;
                String frompart = "";
                String topart = "";
                String fromcode = "";
                String tocode = "";
                String datetype = "";
                
                
                if (fromPart.getText().isEmpty()) {
                    frompart = bsmf.MainFrame.lowchar;
                } else {
                    frompart = fromPart.getText();
                }
                 if (toPart.getText().isEmpty()) {
                    topart = bsmf.MainFrame.hichar;
                } else {
                    topart = toPart.getText();
                }
                  if (fromCode.getText().isEmpty()) {
                    fromcode = bsmf.MainFrame.lowchar;
                } else {
                    fromcode = fromCode.getText();
                }
                   if (toCode.getText().isEmpty()) {
                    tocode = bsmf.MainFrame.hichar;
                } else {
                    tocode = toCode.getText();
                }
                 
                   if (( BlueSeerUtils.boolToInt(cbassydate.isSelected()) + BlueSeerUtils.boolToInt(cbkeydate.isSelected())) != 1 ) {
                       bsmf.MainFrame.show("Must Select only one Date checkbox");
                       return;
                   }
                   
                  
                   if (cbassydate.isSelected()) {
                       datetype = "tr_assy_date";
                   }
                   if (cbkeydate.isSelected()) {
                       datetype = "tr_ent_date";
                   }
                       
                   
               //  ScrapReportPanel.MyTableModel mymodel = new ScrapReportPanel.MyTableModel(new Object[][]{},
               //         new String[]{"Acct", "Description", "Amt"});
               // tablescrap.setModel(mymodel);
               
                   
                   
                   
                ScrapReportPanel.MyTableModel mymodel = new ScrapReportPanel.MyTableModel(new Object[][]{},
                        new String[]{"Part", "P/M", "Qty", "Cost", "Operation", "AssyDate", "Code", "WorkCell", "TimeStamp", "Userid"});
                tablescrap.setModel(mymodel);
                tablescrap.getColumnModel().getColumn(0).setCellRenderer(new ScrapReportPanel.SomeRenderer());  
                
                // TableColumnModel tcm = tablescrap.getColumnModel();
               // tcm.getColumn(3).setCellRenderer(BlueSeerUtils.NumberRenderer.getCurrencyRenderer());  
                
                 

                 
                  if (cbsumpart.isSelected() && cbsumcode.isSelected()) {
                res = st.executeQuery("SELECT tr_part, tr_type, it_code, sum(tr_qty) as tr_qty, " +
                        " tr_op, tr_eff_date, tr_assy_date, tr_ref, tr_actcell,  " +
                        " case when it_code = 'M' then itr_total else itc_total end as amt,  " +
                        " sum(case when it_code = 'M' then itr_total else itc_total end * tr_qty) as tot,  " +
                        " tr_timestamp, tr_export, tr_userid, tr_pack, tr_pack_date " +
                        " FROM  tran_mstr inner join item_mstr on it_item = tr_part " +
                        " left outer join itemr_cost on itr_item = tr_part and itr_op = tr_op and itr_set = 'standard' " +
                        " left outer join item_cost on itc_item = tr_part and itc_set = 'standard' " +
                        " where " + datetype + " >= " + "'" + dfdate.format(dcFrom.getDate()) + "'" + 
                        " AND " + datetype + " <= " + "'" + dfdate.format(dcTo.getDate()) + "'" + 
                        " AND tr_part >= " + "'" + frompart + "'" + 
                        " AND tr_part <= " + "'" + topart + "'" + 
                         " AND tr_ref >= " + "'" + fromcode + "'" + 
                        " AND tr_ref <= " + "'" + tocode + "'" + 
                        " AND tr_type = 'ISS-SCRAP' " +
                        " group by tr_part, tr_ref " + 
                        "   ;");
                 }
                 
                  if (cbsumcode.isSelected() && ! cbsumpart.isSelected()) {
                res = st.executeQuery("SELECT tr_part, tr_type, it_code, sum(tr_qty) as tr_qty, " +
                        " tr_op, tr_eff_date, tr_assy_date, tr_ref, tr_actcell, " +
                        " case when it_code = 'M' then itr_total else itc_total end as amt,  " +
                        " sum(case when it_code = 'M' then itr_total else itc_total end * tr_qty) as tot,  " +
                        " tr_timestamp, tr_export, tr_userid, tr_pack, tr_pack_date " +
                        " FROM  tran_mstr inner join item_mstr on it_item = tr_part " +
                        " left outer join itemr_cost on itr_item = tr_part and itr_op = tr_op and itr_set = 'standard' " +
                        " left outer join item_cost on itc_item = tr_part and itc_set = 'standard' " +
                        " where " + datetype + " >= " + "'" + dfdate.format(dcFrom.getDate()) + "'" + 
                        " AND " + datetype + " <= " + "'" + dfdate.format(dcTo.getDate()) + "'" + 
                        " AND tr_part >= " + "'" + frompart + "'" + 
                        " AND tr_part <= " + "'" + topart + "'" + 
                         " AND tr_ref >= " + "'" + fromcode + "'" + 
                        " AND tr_ref <= " + "'" + tocode + "'" + 
                        " AND tr_type = 'ISS-SCRAP' " +
                        " group by tr_ref " + 
                        "   ;");
                 } 
                  
                 if (cbsumpart.isSelected() && ! cbsumcode.isSelected()) {
                res = st.executeQuery("SELECT tr_part, tr_type, it_code, sum(tr_qty) as tr_qty, " +
                        " tr_op, tr_eff_date, tr_assy_date, tr_ref, tr_actcell, " +
                        " case when it_code = 'M' then itr_total else itc_total end as amt,  " +
                        " sum(case when it_code = 'M' then itr_total else itc_total end * tr_qty) as tot,  " +
                        " tr_timestamp, tr_export, tr_userid, tr_pack, tr_pack_date " +
                        " FROM  tran_mstr inner join item_mstr on it_item = tr_part " +
                        " left outer join itemr_cost on itr_item = tr_part and itr_op = tr_op and itr_set = 'standard' " +
                        " left outer join item_cost on itc_item = tr_part and itc_set = 'standard' " +
                       " where " + datetype + " >= " + "'" + dfdate.format(dcFrom.getDate()) + "'" + 
                        " AND " + datetype + " <= " + "'" + dfdate.format(dcTo.getDate()) + "'" + 
                        " AND tr_part >= " + "'" + frompart + "'" + 
                        " AND tr_part <= " + "'" + topart + "'" + 
                         " AND tr_ref >= " + "'" + fromcode + "'" + 
                        " AND tr_ref <= " + "'" + tocode + "'" + 
                        " AND tr_type = 'ISS-SCRAP' " +
                        " group by tr_part " + 
                        "   ;");
                 } 
                 
                 
                 if (! cbsumpart.isSelected() && ! cbsumcode.isSelected()) {
                 res = st.executeQuery("SELECT tr_part, tr_type, it_code, tr_qty, " +
                        " tr_op, tr_eff_date, tr_assy_date, tr_ref, tr_actcell, " +
                        " case when it_code = 'M' then itr_total else itc_total end as amt,  " +
                         " tr_timestamp, tr_export, tr_userid, tr_pack, tr_pack_date " +
                        " FROM  tran_mstr inner join item_mstr on it_item = tr_part " +
                        " left outer join itemr_cost on itr_item = tr_part and itr_op = tr_op and itr_set = 'standard' " +
                         " left outer join item_cost on itc_item = tr_part and itc_set = 'standard' " +
                        " where " + datetype + " >= " + "'" + dfdate.format(dcFrom.getDate()) + "'" + 
                        " AND " + datetype + " <= " + "'" + dfdate.format(dcTo.getDate()) + "'" + 
                        " AND tr_part >= " + "'" + frompart + "'" + 
                        " AND tr_part <= " + "'" + topart + "'" + 
                         " AND tr_ref >= " + "'" + fromcode + "'" + 
                        " AND tr_ref <= " + "'" + tocode + "'" + 
                        " AND tr_type = 'ISS-SCRAP' " + 
                        " order by tr_id desc ;");    
                 }
                 
                while (res.next()) {
                    i++;
                    
                    if (cbsumpart.isSelected() && ! cbsumcode.isSelected()) {
                   qty = qty + res.getInt("tr_qty");
                    dol = dol + res.getDouble("tot");
                        mymodel.addRow(new Object[]{
                                res.getString("tr_part"),
                                res.getString("it_code"),
                                res.getInt("tr_qty"),
                                res.getDouble("tot"),
                                null,
                                null,
                                null,
                                null,
                                null,
                                null
                            });
                    } else if (cbsumcode.isSelected() && ! cbsumpart.isSelected()) {
                   qty = qty + res.getInt("tr_qty");
                    dol = dol + res.getDouble("tot");
                         mymodel.addRow(new Object[]{
                                null,
                                null,
                                res.getInt("tr_qty"),
                                res.getDouble("tot"),
                                null,
                                null,
                                res.getString("tr_ref"),
                                null,
                                null,
                                null
                            });
                    }
                    else if (cbsumcode.isSelected() &&  cbsumpart.isSelected()) {
                   qty = qty + res.getInt("tr_qty");
                    dol = dol + res.getDouble("tot");
                         mymodel.addRow(new Object[]{
                                res.getString("tr_part"),
                                res.getString("it_code"),
                                res.getInt("tr_qty"),
                                res.getDouble("tot"),
                                null,
                                null,
                                res.getString("tr_ref"),
                                null,
                                null,
                                null
                            });
                    }
                    else {
                   qty = qty + res.getInt("tr_qty");
                    dol = dol + (res.getDouble("amt") * res.getInt("tr_qty"));
                         mymodel.addRow(new Object[]{res.getString("tr_part"),
                                res.getString("it_code"),
                                res.getInt("tr_qty"),
                                res.getDouble("amt"),
                                res.getInt("tr_op"),
                                res.getString("tr_assy_date"),
                                res.getString("tr_ref"),
                                res.getString("tr_actcell"),
                                res.getString("tr_timestamp"),
                                res.getString("tr_userid")
                            });
                    }
                }
                labeldollar.setText(String.valueOf(df.format(dol)));
                labelcount.setText(String.valueOf(i));
                labelqty.setText(String.valueOf(qty));
            } catch (SQLException s) {
                bsmf.MainFrame.show("Cannot execute sql query for Scrap Report");
            }
            con.close();
        } catch (Exception e) {
            MainFrame.bslog(e);
        }
       
    }//GEN-LAST:event_btRunActionPerformed

    private void btexportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexportActionPerformed
       FileDialog fDialog;
        fDialog = new FileDialog(new Frame(), "Save", FileDialog.SAVE);
        fDialog.setVisible(true);
        //fDialog.setFile("data.csv");
        String path = fDialog.getDirectory() + fDialog.getFile();
        File f = new File(path);
        BufferedWriter output;
        
         int i = 0;
           int qty = 0;
                double dol = 0;
                DecimalFormat df = new DecimalFormat("###,###,###.##");
                String frompart = "";
                String topart = "";
                String fromcode = "";
                String tocode = "";
                String datetype = "";
                
                if (fromPart.getText().isEmpty()) {
                    frompart = bsmf.MainFrame.lowchar;
                } else {
                    frompart = fromPart.getText();
                }
                 if (toPart.getText().isEmpty()) {
                    topart = bsmf.MainFrame.hichar;
                } else {
                    topart = toPart.getText();
                }
                  if (fromCode.getText().isEmpty()) {
                    fromcode = bsmf.MainFrame.lowchar;
                } else {
                    fromcode = fromCode.getText();
                }
                   if (toCode.getText().isEmpty()) {
                    tocode = bsmf.MainFrame.hichar;
                } else {
                    tocode = toCode.getText();
                }
                   
                    if ((BlueSeerUtils.boolToInt(cbassydate.isSelected()) + BlueSeerUtils.boolToInt(cbkeydate.isSelected())) != 1 ) {
                       bsmf.MainFrame.show("Must Select only one Date checkbox");
                       return;
                   }
                   
                
                   if (cbassydate.isSelected()) {
                       datetype = "tr_assy_date";
                   }
                   if (cbkeydate.isSelected()) {
                       datetype = "tr_ent_date";
                   }
                   
           DateFormat dfdate = new SimpleDateFormat("yyyy-MM-dd");
        try {
            output = new BufferedWriter(new FileWriter(f));
               String myheader = "";
                if (cbsumpart.isSelected() && ! cbsumcode.isSelected()) {
                myheader = "Part,Code,Qty,Tot";
                output.write(myheader + '\n');
                } else if (cbsumcode.isSelected() && ! cbsumpart.isSelected()) {
                     myheader = "Qty,Tot,Ref";
                output.write(myheader + '\n');
                } else if (cbsumcode.isSelected() &&  cbsumpart.isSelected()) {
                      myheader = "Part,Code,Qty,Op,Ref";
                output.write(myheader + '\n');     
                } else {
                     myheader = "Part,Code,Qty,Amt,Op,EffDate,Ref,Dept/Cell,AssyDate";
                output.write(myheader + '\n');     
                }
                
              
                 
                 
        try {
            Class.forName(driver).newInstance();
            con = DriverManager.getConnection(url + db, user, pass);
            try {
                Statement st = con.createStatement();
                ResultSet res = null;

               
                  if (cbsumpart.isSelected() && cbsumcode.isSelected()) {
                  res = st.executeQuery("SELECT tr_part, tr_type, it_code, sum(tr_qty) as tr_qty, " +
                        " tr_op, tr_eff_date, tr_assy_date, tr_ref, tr_actcell,  " +
                        " case when it_code = 'M' then itr_total else itc_total end as amt,  " +
                        " sum(case when it_code = 'M' then itr_total else itc_total end * tr_qty) as tot,  " +
                        " tr_timestamp, tr_export, tr_userid, tr_pack, tr_pack_date " +
                        " FROM  tran_mstr inner join item_mstr on it_item = tr_part " +
                        " left outer join itemr_cost on itr_item = tr_part and itr_op = tr_op and itr_set = 'standard'" +
                        " left outer join item_cost on itc_item = tr_part and itc_set = 'standard' " +
                        " where " + datetype + " >= " + "'" + dfdate.format(dcFrom.getDate()) + "'" + 
                        " AND " + datetype + " <= " + "'" + dfdate.format(dcTo.getDate()) + "'" + 
                        " AND tr_part >= " + "'" + frompart + "'" + 
                        " AND tr_part <= " + "'" + topart + "'" + 
                         " AND tr_ref >= " + "'" + fromcode + "'" + 
                        " AND tr_ref <= " + "'" + tocode + "'" + 
                        " AND tr_type = 'ISS-SCRAP' " +
                        " group by tr_part, tr_ref " + 
                        "   ;");
                 }
                 
                  if (cbsumcode.isSelected() && ! cbsumpart.isSelected()) {
                res = st.executeQuery("SELECT tr_part, tr_type, it_code, sum(tr_qty) as tr_qty, " +
                        " tr_op, tr_eff_date, tr_assy_date, tr_ref, tr_actcell, " +
                        " case when it_code = 'M' then itr_total else itc_total end as amt,  " +
                        " sum(case when it_code = 'M' then itr_total else itc_total end * tr_qty) as tot,  " +
                        " tr_timestamp, tr_export, tr_userid, tr_pack, tr_pack_date " +
                        " FROM  tran_mstr inner join item_mstr on it_item = tr_part " +
                        " left outer join itemr_cost on itr_item = tr_part and itr_op = tr_op and itr_set = 'standard'" +
                        " left outer join item_cost on itc_item = tr_part and itc_set = 'standard' " +
                        " where " + datetype + " >= " + "'" + dfdate.format(dcFrom.getDate()) + "'" + 
                        " AND " + datetype + " <= " + "'" + dfdate.format(dcTo.getDate()) + "'" + 
                        " AND tr_part >= " + "'" + frompart + "'" + 
                        " AND tr_part <= " + "'" + topart + "'" + 
                         " AND tr_ref >= " + "'" + fromcode + "'" + 
                        " AND tr_ref <= " + "'" + tocode + "'" + 
                        " AND tr_type = 'ISS-SCRAP' " +
                        " group by tr_ref " + 
                        "   ;");
                 } 
                  
                 if (cbsumpart.isSelected() && ! cbsumcode.isSelected()) {
                res = st.executeQuery("SELECT tr_part, tr_type, it_code, sum(tr_qty) as tr_qty, " +
                        " tr_op, tr_eff_date, tr_assy_date, tr_ref, tr_actcell, " +
                        " case when it_code = 'M' then itr_total else itc_total end as amt,  " +
                        " sum(case when it_code = 'M' then itr_total else itc_total end * tr_qty) as tot,  " +
                        " tr_timestamp, tr_export, tr_userid, tr_pack, tr_pack_date " +
                        " FROM  tran_mstr inner join item_mstr on it_item = tr_part " +
                        " left outer join itemr_cost on itr_item = tr_part and itr_op = tr_op and itr_set = 'standard'" +
                        " left outer join item_cost on itc_item = tr_part and itc_set = 'standard' " +
                       " where " + datetype + " >= " + "'" + dfdate.format(dcFrom.getDate()) + "'" + 
                        " AND " + datetype + " <= " + "'" + dfdate.format(dcTo.getDate()) + "'" + 
                        " AND tr_part >= " + "'" + frompart + "'" + 
                        " AND tr_part <= " + "'" + topart + "'" + 
                         " AND tr_ref >= " + "'" + fromcode + "'" + 
                        " AND tr_ref <= " + "'" + tocode + "'" + 
                        " AND tr_type = 'ISS-SCRAP' " +
                        " group by tr_part " + 
                        "   ;");
                 } 
                 
                 
                 if (! cbsumpart.isSelected() && ! cbsumcode.isSelected()) {
                
                 res = st.executeQuery("SELECT tr_part, tr_type, it_code, tr_qty, " +
                        " tr_op, tr_eff_date, tr_assy_date, tr_ref, tr_actcell, " +
                        " case when it_code = 'M' then itr_total else itc_total end as amt,  " +
                         " tr_timestamp, tr_export, tr_userid, tr_pack, tr_pack_date " +
                        " FROM  tran_mstr inner join item_mstr on it_item = tr_part " +
                        " left outer join itemr_cost on itr_item = tr_part and itr_op = tr_op and itr_set = 'standard'" +
                         " left outer join item_cost on itc_item = tr_part and itc_set = 'standard' " +
                        " where " + datetype + " >= " + "'" + dfdate.format(dcFrom.getDate()) + "'" + 
                        " AND " + datetype + " <= " + "'" + dfdate.format(dcTo.getDate()) + "'" + 
                        " AND tr_part >= " + "'" + frompart + "'" + 
                        " AND tr_part <= " + "'" + topart + "'" + 
                         " AND tr_ref >= " + "'" + fromcode + "'" + 
                        " AND tr_ref <= " + "'" + tocode + "'" + 
                        " AND tr_type = 'ISS-SCRAP' " + 
                        " order by tr_id desc ;");    
                 
                 }

                
                while (res.next()) {
                    i++;
                    
                    if (cbsumpart.isSelected() && ! cbsumcode.isSelected()) {
                   qty = qty + res.getInt("tr_qty");
                    dol = dol + res.getDouble("tot");
                     String newstring = res.getString("tr_part") + "," + res.getString("it_code").replace(",","") + "," + 
                            res.getString("tr_qty") + "," + res.getDouble("tot");
                    output.write(newstring + '\n');
                       
                    } else if (cbsumcode.isSelected() && ! cbsumpart.isSelected()) {
                   qty = qty + res.getInt("tr_qty");
                    dol = dol + res.getDouble("tot");
                     String newstring = 
                            res.getInt("tr_qty") + "," + res.getDouble("tot") + "," + 
                            res.getString("tr_ref") ;
                    output.write(newstring + '\n');
                    }
                    else if (cbsumcode.isSelected() &&  cbsumpart.isSelected()) {
                   qty = qty + res.getInt("tr_qty");
                    dol = dol + res.getDouble("tot");
                    String newstring = res.getString("tr_part") + "," + res.getString("it_code").replace(",","") + "," + 
                            res.getInt("tr_qty") + "," + res.getDouble("tr_op") + "," + 
                            res.getString("tr_ref") ;
                            
                    output.write(newstring + '\n');
                    }
                    else {
                   qty = qty + res.getInt("tr_qty");
                    dol = dol + (res.getDouble("amt") * res.getInt("tr_qty"));
                    String newstring = res.getString("tr_part") + "," + res.getString("it_code").replace(",","") + "," + 
                            res.getInt("tr_qty") + "," + res.getDouble("amt") + "," + res.getInt("tr_op") + "," + res.getString("tr_eff_date") + "," + 
                            res.getString("tr_ref") + "," + res.getString("tr_actcell") + ","  + res.getString("tr_assy_date") ;
                           output.write(newstring + '\n');
                        
                    }
                }
                
                
                
             bsmf.MainFrame.show("file has been created");
            } catch (SQLException s) {
                bsmf.MainFrame.show("Cannot extract tran_mstr data");
            }
            con.close();
        } catch (Exception e) {
            MainFrame.bslog(e);
        }
        
        
        output.close();
        
        
        
        } catch (IOException ex) {
            Logger.getLogger(bsmf.MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btexportActionPerformed

    private void tablescrapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablescrapMouseClicked
        int row = tablescrap.rowAtPoint(evt.getPoint());
        int col = tablescrap.columnAtPoint(evt.getPoint());
        if ( col == 0) {
              if (! checkperms("MenuItemMastMaint")) { return; }
                bsmf.MainFrame.reinitpanels("MenuItemMastMaint", true, tablescrap.getValueAt(row, col).toString());
        }
    }//GEN-LAST:event_tablescrapMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRun;
    private javax.swing.JButton btexport;
    private javax.swing.JCheckBox cbassydate;
    private javax.swing.JCheckBox cbkeydate;
    private javax.swing.JCheckBox cbsumcode;
    private javax.swing.JCheckBox cbsumpart;
    private com.toedter.calendar.JDateChooser dcFrom;
    private com.toedter.calendar.JDateChooser dcTo;
    private javax.swing.JTextField fromCode;
    private javax.swing.JTextField fromPart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelcount;
    private javax.swing.JLabel labeldollar;
    private javax.swing.JLabel labelqty;
    private javax.swing.JTable tablescrap;
    private javax.swing.JTextField toCode;
    private javax.swing.JTextField toPart;
    // End of variables declaration//GEN-END:variables
}
