
package com.blueseer.pur;

import com.blueseer.utl.OVData;
import com.blueseer.utl.BlueSeerUtils;
import static bsmf.MainFrame.backgroundcolor;
import static bsmf.MainFrame.backgroundpanel;
import java.awt.Color;
import java.awt.GradientPaint;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author vaughnte
 */


public class ReqControl extends javax.swing.JPanel {

    
     javax.swing.table.DefaultTableModel authmodel = new javax.swing.table.DefaultTableModel(new Object[][]{},
            new String[]{
                "Userid", "Desc", "Seqeunce", "Enabled", "Email"
            });
    
    /**
     * Creates new form ClockControl
     */
    public ReqControl() {
        initComponents();
    }

    
     public void getcontrol() {
         try {

            Class.forName(bsmf.MainFrame.driver).newInstance();
            bsmf.MainFrame.con = DriverManager.getConnection(bsmf.MainFrame.url + bsmf.MainFrame.db, bsmf.MainFrame.user, bsmf.MainFrame.pass);
            try {
                Statement st = bsmf.MainFrame.con.createStatement();
                ResultSet res = null;
                
                int i = 0;
                    res = st.executeQuery("SELECT * FROM  req_ctrl;");
                    while (res.next()) {
                        i++;
                        String[] admins = res.getString("req_admins").split(",", -1);
                        for (String admin : admins) {
                            ddadmins.addItem(admin);
                        }
                        tbthreshold.setText(res.getString("req_amt_threshold"));
                        cbrequestor.setSelected(res.getBoolean("req_requestor_email"));
                       
                    }
                    res = st.executeQuery("SELECT * FROM  req_auth;");
                    while (res.next()) {
                     authmodel.addRow(new Object[]{res.getString("reqa_owner"), res.getString("reqa_desc"), res.getString("reqa_sequence"), res.getBoolean("reqa_enabled"), res.getBoolean("reqa_email")});   
                    }
           
            }
            catch (SQLException s) {
                bsmf.MainFrame.show("Unable to retrieve req_ctrl");
            }
            bsmf.MainFrame.con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
     }
    
    
    public void initvars(String arg) {
           
           cbrequestor.setSelected(false);
           authmodel.setRowCount(0);
           tableauth.setModel(authmodel);
           ddadmins.removeAllItems();
           ddallusers.removeAllItems();
           dduserid.removeAllItems();
           ArrayList<String> users = OVData.getusermstrlist();
           for (String user : users) {
               dduserid.addItem(user);
               ddallusers.addItem(user);
           }
           
           tbsequence.setText("");
           tbdesc.setText("");
           cbemail.setSelected(false);
           cbenabled.setSelected(false);
           
           getcontrol();
           
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btupdate = new javax.swing.JButton();
        tbthreshold = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbemail = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        ddallusers = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableauth = new javax.swing.JTable();
        tbsequence = new javax.swing.JTextField();
        cbenabled = new javax.swing.JCheckBox();
        btdeleteauth = new javax.swing.JButton();
        tbdesc = new javax.swing.JTextField();
        btaddauth = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btdelete = new javax.swing.JButton();
        dduserid = new javax.swing.JComboBox<>();
        btadd = new javax.swing.JButton();
        ddadmins = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbrequestor = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(0, 102, 204));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Requisition Control"));

        btupdate.setText("Update");
        btupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btupdateActionPerformed(evt);
            }
        });

        jLabel1.setText("Threshold Amt:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Authorization Maintenance"));

        cbemail.setText("Emailed?");

        jLabel2.setText("Sequence");

        jLabel3.setText("Desc");

        tableauth.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableauth);

        cbenabled.setText("Enabled?");

        btdeleteauth.setText("Delete");
        btdeleteauth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteauthActionPerformed(evt);
            }
        });

        btaddauth.setText("Add");
        btaddauth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddauthActionPerformed(evt);
            }
        });

        jLabel4.setText("User");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ddallusers, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbsequence, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbemail)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbenabled)
                                .addGap(27, 27, 27)
                                .addComponent(btaddauth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btdeleteauth))))
                    .addComponent(tbdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddallusers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbenabled)
                    .addComponent(btaddauth)
                    .addComponent(btdeleteauth)
                    .addComponent(tbsequence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbemail)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("PreApproved List"));

        btdelete.setText("Delete");
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });

        btadd.setText("Add");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });

        jLabel5.setText("All Users");

        jLabel6.setText("PreApproved Users");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dduserid, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ddadmins, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btadd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btdelete)
                .addGap(38, 38, 38))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btadd)
                    .addComponent(btdelete)
                    .addComponent(ddadmins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(dduserid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        cbrequestor.setText("Requestor Email?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbrequestor)
                    .addComponent(btupdate)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbthreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbthreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbrequestor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btupdate)
                .addContainerGap())
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void btupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btupdateActionPerformed
        try {

            Class.forName(bsmf.MainFrame.driver).newInstance();
            bsmf.MainFrame.con = DriverManager.getConnection(bsmf.MainFrame.url + bsmf.MainFrame.db, bsmf.MainFrame.user, bsmf.MainFrame.pass);
            try {
                Statement st = bsmf.MainFrame.con.createStatement();
                ResultSet res = null;
                boolean proceed = true;
                int i = 0;
                int threshold = 0;
                if (! tbthreshold.getText().isEmpty())
                threshold = Integer.valueOf(tbthreshold.getText());
                
              ArrayList<String> admins = new ArrayList<String>();
               for (int j = 0; j < ddadmins.getItemCount(); j++) {
                   admins.add(ddadmins.getItemAt(j).toString());
               }
               String adminsstring = String.join(",", admins);
                
                res = st.executeQuery("SELECT *  FROM  req_ctrl ;");
                    while (res.next()) {
                        i++;
                    }
                if (i == 0) {
                    
                    st.executeUpdate("insert into req_ctrl (req_admins, req_amt_threshold, req_requestor_email) values (" + 
                            "'" + adminsstring + "'" + "," +
                            "'" + threshold + "'"  + "," +
                            "'" + BlueSeerUtils.boolToInt(cbrequestor.isSelected()) + "'" +
                            ")" + ";");              
                          bsmf.MainFrame.show("Inserting Defaults");
                } else {
                    st.executeUpdate("update req_ctrl set " 
                            + " req_admins = " + "'" + adminsstring + "'" + "," 
                            + " req_requestor_email = " + "'" + BlueSeerUtils.boolToInt(cbrequestor.isSelected()) + "'" + "," +
                            " req_amt_threshold = " + "'" + threshold + "'" + 
                            
                            ";");   
                   
                    
                  
                }
                
                
                //  now lets do req_auth  ....first delete all from req_auth...then add back from table
                st.executeUpdate("delete from req_auth;");
                 for (int j = 0; j < tableauth.getRowCount(); j++) {
                st.executeUpdate("insert into req_auth values ( " 
                        + "'" + tableauth.getValueAt(j, 0).toString() + "'" + ","
                        + "'" + tableauth.getValueAt(j, 1).toString() + "'" + ","
                        + "'" + tableauth.getValueAt(j, 2).toString() + "'" + ","
                        + "'" + BlueSeerUtils.boolToInt(Boolean.valueOf(tableauth.getValueAt(j, 3).toString())) + "'" + ","
                        + "'" + BlueSeerUtils.boolToInt(Boolean.valueOf(tableauth.getValueAt(j, 4).toString())) + "'" 
                        + " );" );
                 }
              
                 bsmf.MainFrame.show("Updated Defaults");
                 
            } catch (SQLException s) {
                bsmf.MainFrame.show("Problem updating req_ctrl and req_auth");
            }
            bsmf.MainFrame.con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btupdateActionPerformed

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
       if(((DefaultComboBoxModel)ddadmins.getModel()).getIndexOf(dduserid.getSelectedItem().toString()) == -1) {
         ddadmins.addItem(dduserid.getSelectedItem().toString());
       } else {
           bsmf.MainFrame.show("Already assigned");
       }
    }//GEN-LAST:event_btaddActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
       int i = ddadmins.getSelectedIndex();
       ddadmins.removeItemAt(i);
    }//GEN-LAST:event_btdeleteActionPerformed

    private void btaddauthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddauthActionPerformed
         authmodel.addRow(new Object[]{ddallusers.getSelectedItem().toString(), tbdesc.getText(), tbsequence.getText(), cbenabled.isSelected(), cbemail.isSelected()});
    }//GEN-LAST:event_btaddauthActionPerformed

    private void btdeleteauthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteauthActionPerformed
       int[] rows = tableauth.getSelectedRows();
        for (int i : rows) {
            bsmf.MainFrame.show("Removing row " + i);
            ((javax.swing.table.DefaultTableModel) tableauth.getModel()).removeRow(i);
            
        }
    }//GEN-LAST:event_btdeleteauthActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btaddauth;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btdeleteauth;
    private javax.swing.JButton btupdate;
    private javax.swing.JCheckBox cbemail;
    private javax.swing.JCheckBox cbenabled;
    private javax.swing.JCheckBox cbrequestor;
    private javax.swing.JComboBox<String> ddadmins;
    private javax.swing.JComboBox<String> ddallusers;
    private javax.swing.JComboBox<String> dduserid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableauth;
    private javax.swing.JTextField tbdesc;
    private javax.swing.JTextField tbsequence;
    private javax.swing.JTextField tbthreshold;
    // End of variables declaration//GEN-END:variables
}
