/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.blueseer.pur;

import com.blueseer.utl.OVData;
import com.blueseer.utl.ReportPanel;
import com.blueseer.utl.BlueSeerUtils;
import java.awt.FileDialog;
import java.awt.Frame;
import java.awt.print.PrinterException;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static bsmf.MainFrame.con;
import static bsmf.MainFrame.db;
import static bsmf.MainFrame.driver;
import static bsmf.MainFrame.mydialog;
import static bsmf.MainFrame.pass;
import static bsmf.MainFrame.url;
import static bsmf.MainFrame.user;
import static com.blueseer.utl.ReportPanel.TableReport;

/**
 *
 * @author vaughnte
 */
public class ReqReportPanel extends javax.swing.JPanel {

     javax.swing.table.DefaultTableModel mymodel = new javax.swing.table.DefaultTableModel(new Object[][]{},
                        new String[]{"ReqID", "Name", "Acct", "CC", "Vend", "Amt", "Status"});
     
    
 
    /**
     * Creates new form CCReportPanel
     */
    public ReqReportPanel() {
        initComponents();
        
    }

    public void initvars(String arg) {
        
           
                tablereport.setModel(mymodel);
    
        
        
         java.util.Date now = new java.util.Date();
        DateFormat dfdate = new SimpleDateFormat("yyyy-MM-dd");
        dcfrom.setDate(now);
        dcto.setDate(now);
        
        
        if (cbuserfrom.getItemCount() == 0) {
        ArrayList users = OVData.getusermstrlist();
        for (int i = 0; i < users.size(); i++) {
            cbuserfrom.addItem(users.get(i));
        }
        } else {
             cbuserfrom.setSelectedIndex(0);
        }
        
         if (cbuserto.getItemCount() == 0) {
        ArrayList users = OVData.getusermstrlist();
        for (int i = 0; i < users.size(); i++) {
            cbuserto.addItem(users.get(i));
        }
        } else {
             cbuserto.setSelectedIndex(0);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablereport = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dcfrom = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        dcto = new com.toedter.calendar.JDateChooser();
        btview = new javax.swing.JButton();
        cbuserto = new javax.swing.JComboBox();
        cbuserfrom = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 204));

        tablereport.setAutoCreateRowSorter(true);
        tablereport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablereport);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Date From:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        dcfrom.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(dcfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 140, -1));

        jLabel1.setText("Date To:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        dcto.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(dcto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 140, -1));

        btview.setText("View");
        btview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btviewActionPerformed(evt);
            }
        });
        jPanel1.add(btview, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jPanel1.add(cbuserto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 140, -1));

        jPanel1.add(cbuserfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 140, -1));

        jLabel3.setText("User To:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jLabel4.setText("User From:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btviewActionPerformed
        mymodel.setNumRows(0);
        try {
            Class.forName(driver).newInstance();
            con = DriverManager.getConnection(url + db, user, pass);
            try {
                Statement st = con.createStatement();
                ResultSet res = null;

                int i = 0;


res = st.executeQuery("SELECT * FROM  req_mstr where " + 
                              " req_date >= " + "'" + BlueSeerUtils.setDateFormat(dcfrom.getDate()) + "'" +
                              " AND req_date <= " + "'" + BlueSeerUtils.setDateFormat(dcto.getDate()) + "'" +
                               "AND req_name >= " + "'" + cbuserfrom.getSelectedItem().toString() + "'" +
                               "AND req_name <= " + "'" + cbuserto.getSelectedItem().toString() + "'" +
                              " order by abs(req_id) desc;"
                              );
                while (res.next()) {
                    i++;

                    mymodel.addRow(new Object[]{res.getString("req_id"),
                                res.getString("req_name"),
                                res.getString("req_acct"),
                                res.getString("req_cc"),
                                res.getString("req_vend"),
                                res.getString("req_amt"),
                                res.getString("req_status")
                                });
                }


            } catch (SQLException s) {
                bsmf.MainFrame.show("Cannot retrieve req records");
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btviewActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try { 
            TableReport.setModel(mymodel);
            
        TableReport.print(JTable.PrintMode.FIT_WIDTH);
       
    
// TODO add your handling code here:
    } catch (PrinterException ex) {
        Logger.getLogger(ReportPanel.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btview;
    private javax.swing.JComboBox cbuserfrom;
    private javax.swing.JComboBox cbuserto;
    private com.toedter.calendar.JDateChooser dcfrom;
    private com.toedter.calendar.JDateChooser dcto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablereport;
    // End of variables declaration//GEN-END:variables
}
